name: Deploy

on:
  push:
    branches:
      - main

env: 
  VITE_APP_CLIENT_ID: ${{ secrets.VITE_APP_CLIENT_ID }}
  VITE_APP_TENANT_ID: ${{ secrets.VITE_APP_TENANT_ID }}
  VITE_APP_REDIRECT_URI: ${{ secrets.VITE_APP_REDIRECT_URI }}
  VITE_OPEN_AI_KEY: ${{ secrets.VITE_OPEN_AI_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist